module Contenter
  # Represents bulk content.
  class Bulk
    def initialize hash = nil
      hash ||= { }
      @hash = hash
      @hash[:api_version] ||= 1
      @hash[:error] ||= nil
      @hash[:results_columns] ||=
        [
         :id,
         :uuid,
         :content_type,
         :content_key,
         :language,
         :country,
         :brand,
         :application,
         :mime_type,
         :md5sum,
         :data,
        ]
    end


    def results
      @hash[:results]
    end


    def render_csv fh = nil
      raise Exception, "not implemented"
    end


    # Renders YAML document representing the content
    # as an array of arrays with list of column names.
    def render_yaml fh = nil
      fh ||= StringIO.new

      document = @hash
      cols = document[:results_columns]
      fh.puts <<"END"
# THIS IS UTF-8 YAML: CHECK YOUR EDITOR SETTINGS BEFORE EDITING IT!
# GENERATED BY Contenter::Bulk#render_yaml
--- 
:api_version: #{document[:api_version]}
END
      if x = document[:action]
        fh.puts ":action: #{x.to_s.inspect}" 
      end

      if x = document[:errors]
        fh.puts ":errors: #{x.inspect}" 
      end

      if x = document[:stats]
        fh.puts ":stats:"
        x.each do | k, v |
          fh.puts "  #{k.inspect}: #{v.inspect}"
        end
      end

      if document[:results]
        document[:result_count] = document[:results].size
        fh.puts <<"END"
:results_count: #{document[:results_count]}
:results_columns: #{document[:results_columns].inspect}
:results: 
END
        row_i = -1
      document[:results].each do | r |
        case r
        when Hash
          r = cols.map { | c | r[c] }
        when Array
          #
        when ActiveRecord::Base
          r = cols.map { | c | r.send(c) }
        else
          raise ArgumentError
        end
        
          fh.puts "# #{row_i += 1}"
        cols.each_with_index do | c, i |
          v = r[i]
          fh.write "#{i == 0 ? '-' : ' '} - "

          case c
          when :data
            if (v =~ /\n/)
              fh.puts <<"END"
|
    #{v.gsub(/(\r?\n)/){|x| x + "    "}}
END
            else
              fh.puts <<"END"
"#{v.gsub(/([\\\"])/){|x| '\\' + x }}"
END
            end
          when :content_key
            fh.puts "#{v.inspect}"
          when :version, :id, :uuid, :md5sum
            fh.puts "#{v}"
          else
            fh.puts ":#{v.inspect}"
          end
        end
      end
      end

      fh
    end
  end # class
end # module

