--- 
applications_001: 
  name: Any Application
  created_at: 2009-06-26 22:05:12.698209
  code: _
  updated_at: 2009-06-26 22:05:12.698209
  lock_version: "0"
  updater_user_id: 
  id: "1"
  creator_user_id: "1"
  description: Wildcard
applications_003: 
  name: Test Application
  created_at: 2009-06-26 22:05:12.709641
  code: test
  updated_at: 2009-06-26 22:05:12.709641
  lock_version: "0"
  updater_user_id: 
  id: "3"
  creator_user_id: "1"
  description: For testing
